### ISSUE TITLE
Image Axes Change

### ISSUE THREAD

**Issue by samuelgerber** [InsightSoftwareConsortium/ITKTotalVariation#26]
The total variation can flip the image axis depending on the input orientation:

I assume it's because the temporary double output image here:
https://github.com/InsightSoftwareConsortium/ITKTotalVariation/blob/ada39a5cb841ef06b89cea94a587ccddaa389e2d/include/itkProxTVImageFilter.hxx#L70
is not copying all the meta information from the input image.

**Comment by phcerdan** [comment]
Thanks @samuelgerber, what do you think about adding a `ChangeInformationTypeFilter` after casting it here:
https://github.com/InsightSoftwareConsortium/ITKTotalVariation/blob/ada39a5cb841ef06b89cea94a587ccddaa389e2d/include/itkProxTVImageFilter.hxx#L121

Not sure if it is better there, or just after instantiating the `resultImage`.

**Comment by samuelgerber** [comment]
Either that or:
resultImage->CopyInformation( input );

Is there any reason to prefer one or the other?

**Comment by phcerdan** [comment]
That sounds better. Did it solve the problem?
If yes, please open a PR with your fix, and I'll merge asap.

**Comment by phcerdan** [comment]
Closed via #27
