### ISSUE TITLE
wrappings for python 3.9 not in pypi

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/ITKTotalVariation#41]
https://pypi.org/project/itk-totalvariation/#files

**Comment by thewtex** [comment]
This will be addressed with #42

**Comment by thewtex** [comment]
@phcerdan if you want to do the honors, adding a `v0.2.1` tag will push the packages to PyPI.

**Comment by phcerdan** [comment]
Not sure if I did it all right, I manually created a release with the tag v0.2.1

**Comment by phcerdan** [comment]
Thanks @thewtex!
